[package]
name = "bash-chat"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
dotenv = "0.15"  # Check for the latest version on crates.io
sysinfo = "0.32.0"
bincode = "1.3"
serde = "*"
rand = "8"


[[bin]]
name = "server"
path = "src/bin/server/main.rs"