[package]
name = "election"
version = "0.1.0"
edition = "2021"

[dependencies]
steganography = "*"
image = "0.21"
imageproc = "0.23"
fs= "*"
bincode = "*"
rand = "*"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }